default_target = "raspberrypi4"
supported_targets = ["raspberrypi4"]

[ext.avocado-bsp-raspberrypi4]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "Board support for the Raspberry Pi 4"
description = "Board support for the Raspberry Pi 4"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-ext"
types = ["sysext", "confext"]
on_merge = ["udevadm trigger --action=add"]

[ext.avocado-bsp-raspberrypi4.dependencies]
kernel-module-v3d = "*"
kernel-module-gpu-sched = "*"
kernel-module-drm-shmem-helper = "*"
kernel-module-brcmfmac = "*"
kernel-module-brcmutil = "*"
kernel-module-hci-uart = "*"
kernel-module-btbcm = "*"
kernel-module-bluetooth = "*"
kernel-module-cfg80211 = "*"
kernel-module-ecdh-generic = "*"
kernel-module-ecc = "*"
kernel-module-bcm2835-isp = "*"
kernel-module-bcm2835-codec = "*"
kernel-module-libaes = "*"
kernel-module-bcm2835-v4l2 = "*"
kernel-module-rfkill = "*"
kernel-module-bcm2835-mmal-vchiq = "*"
kernel-module-raspberrypi-hwmon = "*"
kernel-module-i2c-brcmstb = "*"
kernel-module-vc-sm-cma = "*"
kernel-module-raspberrypi-gpiomem = "*"
kernel-module-snd-bcm2835 = "*"
kernel-module-videobuf2-vmalloc = "*"
kernel-module-rpi-hevc-dec = "*"
kernel-module-v4l2-mem2mem = "*"
kernel-module-videobuf2-dma-contig = "*"
kernel-module-videobuf2-memops = "*"
kernel-module-videobuf2-v4l2 = "*"
kernel-module-videodev = "*"
kernel-module-videobuf2-common = "*"
kernel-module-mc = "*"
kernel-module-uio-pdrv-genirq = "*"
kernel-module-uio = "*"
kernel-module-fuse = "*"
kernel-module-sch-fq-codel = "*"
kernel-module-ipv6 = "*"

fwup = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"
