default_target = "icam-540"
supported_targets = ["icam-540"]

[ext.avocado-bsp-icam-540]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "Board support for the Advantech ICAM 540"
description = "Board support for the Advantech ICAM 540"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"
types = ["sysext", "confext"]
modprobe = ["gpio-pca953x"]
on_merge = [
  "gpioset -t 500,500,0 -c 2 5=0",
  "udevadm control --reload",
  "udevadm trigger --type=subsystems --action=add --settle",
  "udevadm trigger --type=devices --action=add --settle"
]

[ext.avocado-bsp-icam-540.dependencies]
kernel-module-snd-soc-tegra186-asrc = "*"
kernel-module-snd-soc-tegra210-admaif = "*"
kernel-module-snd-soc-tegra-utils = "*"
kernel-module-snd-soc-tegra210-ope = "*"
kernel-module-snd-soc-tegra210-mixer = "*"
kernel-module-snd-soc-tegra-pcm = "*"
kernel-module-snd-soc-tegra186-arad = "*"
kernel-module-snd-soc-tegra210-mvc = "*"
kernel-module-snd-soc-tegra186-dspk = "*"
kernel-module-snd-soc-tegra210-dmic = "*"
kernel-module-snd-soc-tegra210-adx = "*"
kernel-module-snd-soc-tegra210-amx = "*"
kernel-module-snd-soc-tegra210-sfc = "*"
kernel-module-snd-soc-tegra210-i2s = "*"
kernel-module-snd-soc-tegra210-ahub = "*"
kernel-module-tegra210-adma = "*"
kernel-module-snd-soc-tegra-audio-graph-card = "*"
kernel-module-snd-hda-codec-hdmi = "*"
kernel-module-crct10dif-ce = "*"
kernel-module-crct10dif-common = "*"
kernel-module-aes-ce-blk = "*"
kernel-module-aes-ce-cipher = "*"
kernel-module-ghash-ce = "*"
kernel-module-sha2-ce = "*"
kernel-module-sha256-arm64 = "*"
kernel-module-sha1-ce = "*"
kernel-module-snd-soc-audio-graph-card = "*"
kernel-module-snd-soc-simple-card-utils = "*"
kernel-module-tegra-aconnect = "*"
kernel-module-governor-userspace = "*"
kernel-module-gpio-keys = "*"
kernel-module-snd-hda-tegra = "*"
kernel-module-spidev = "*"
kernel-module-snd-hda-codec = "*"
kernel-module-snd-hda-core = "*"
kernel-module-at24 = "*"
kernel-module-tegra-drm = "*"
kernel-module-drm-display-helper = "*"
kernel-module-drm-dp-aux-bus = "*"
kernel-module-tegra-wmark = "*"
kernel-module-cec = "*"
kernel-module-r8169 = "*"
kernel-module-realtek = "*"
kernel-module-nvvrs-pseq-rtc = "*"
kernel-module-fusb301 = "*"
kernel-module-tegra234-oc-event = "*"
kernel-module-nvpmodel-clk-cap = "*"
kernel-module-thermal-trip-event = "*"
kernel-module-tegra-cactmon-mc-all = "*"
kernel-module-tegra234-aon = "*"
kernel-module-mc-hwpm = "*"
kernel-module-pwm-tegra-tachometer = "*"
kernel-module-spi-tegra114 = "*"
kernel-module-pwm-tegra = "*"
kernel-module-nvhwpm = "*"
kernel-module-tegra-bpmp-thermal = "*"
kernel-module-nvidia-vrs-pseq = "*"
kernel-module-host1x-fence = "*"
kernel-module-nvhost-pva = "*"
kernel-module-nvhost-nvdla = "*"
kernel-module-host1x-nvhost = "*"
kernel-module-pwm-fan = "*"
kernel-module-nvgpu = "*"
kernel-module-governor-pod-scaling = "*"
kernel-module-mc-utils = "*"
kernel-module-nvmap = "*"
kernel-module-nvsciipc = "*"
kernel-module-host1x = "*"
kernel-module-ina3221 = "*"
kernel-module-tegra-xudc = "*"
kernel-module-phy-tegra194-p2u = "*"
kernel-module-pcie-tegra194 = "*"
kernel-module-nvme = "*"
kernel-module-nvme-core = "*"
kernel-module-sch-fq-codel = "*"
kernel-module-gpio-pca953x = "*"
libgpiod-tools = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"
