supported_targets = "*"
src_dir = "../../"

[ext.avocado-ext-cockpit]
version = "0.1.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "Cockpit with web interface"
description = "A web-based graphical interface for device configuration"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"
types = ["sysext", "confext"]
on_merge = ["systemctl restart --no-block cockpit.service"]
enable_services = ["cockpit.service"]

[ext.avocado-ext-cockpit.dependencies]
cockpit = "*"
cockpit-ws = "*"
cockpit-networkmanager = "*"
cockpit-systemd = "*"
cockpit-shell = "*"
cockpit-dashboard = "*"
cockpit-bridge = "*"
coreutils = "*"
bash = "*"
sscg = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"

[sdk.dependencies]
avocado-sdk-toolchain = "*"
