supported_targets = "*"

src_dir = "../../"

[ext.avocado-ext-peridio]
version = "1.0.0"
release = "r0"
vendor = "Avocado Linux <info@avocadolinux.org>"
summary = "Peridio firmware updater"
description = "Peridio firmware updater"
license = "Apache-2.0"
url = "https://github.com/avocadolinux/avocado-os"
types = ["sysext", "confext"]
enable_services = ["peridiod.service"]
overlay = "extensions/peridio/overlay"
on_merge = ["systemctl restart --no-block peridiod.service"]

[ext.avocado-ext-peridio.dependencies]
peridiod = "*"

[sdk]
image = "avocadolinux/sdk:apollo-edge"

[sdk.dependencies]
avocado-sdk-toolchain = "*"
