supported_targets = "*"

##
## Runtimes
##

[runtime.dev.dependencies]
avocado-img-bootfiles = "*"
avocado-img-rootfs = "*"
avocado-img-initramfs = "*"
avocado-ext-dev = { ext = "avocado-ext-dev", vsn = "*" }
avocado-ext-sshd-dev = { ext = "avocado-ext-sshd-dev", vsn = "*" }
config = { ext = "config" }
app = { ext = "app" }

# BSPs
[runtime.dev.reterminal-dm.dependencies]
avocado-bsp-reterminal-dm = { ext = "avocado-bsp-reterminal-dm", vsn = "*" }

[runtime.dev.reterminal.dependencies]
avocado-bsp-reterminal = { ext = "avocado-bsp-reterminal", vsn = "*" }

[runtime.dev.raspberrypi5.dependencies]
avocado-bsp-raspberrypi5 = { ext = "avocado-bsp-raspberrypi5", vsn = "*" }

[runtime.dev.raspberrypi4.dependencies]
avocado-bsp-raspberrypi4 = { ext = "avocado-bsp-raspberrypi4", vsn = "*" }

[runtime.dev.icam-540.dependencies]
avocado-bsp-icam-540 = { ext = "avocado-bsp-icam-540", vsn = "*" }
avocado-img-tegraflash = "*"

[runtime.dev.jetson-orin-nano-devkit.dependencies]
avocado-img-tegraflash = "*"

[runtime.dev.jetson-agx-orin-devkit.dependencies]
avocado-img-tegraflash = "*"

[runtime.dev.rubikpi3.dependencies]
avocado-img-ufs = "*"

##
## Extensions
##

[ext.app]
types = ["sysext", "confext"]
version = "0.1.0"

[ext.app.dependencies]
i2c-tools = "*"

[ext.config]
types = ["confext"]
version = "0.1.0"

[ext.config.users.root]
password = ""

##
## SDK
##

[sdk]
image = "docker.io/avocadolinux/sdk:apollo-edge"

[sdk.dependencies]
avocado-sdk-toolchain = "*"
nativesdk-avocado-hitl = "*"
nativesdk-openssh-ssh = "*"
nativesdk-openssh-scp = "*"
nativesdk-rsync = "*"

[sdk.qemux86-64]
container_args = ["--network=host"]

[sdk.qemuarm64]
container_args = ["--network=host"]

##
## Provisioning
##

[provision.usb]
container_args = ["-v", "/dev:/dev", "-v", "/sys:/sys:ro", "--privileged"]

[provision.sd]
container_args = ["-v", "/dev:/dev", "-v", "/sys:/sys:ro", "--privileged"]

[provision.tegraflash]
container_args = ["-v", "/dev:/dev", "-v", "/sys:/sys:ro", "--privileged"]

[provision.ufs]
container_args = ["-v", "/dev:/dev", "-v", "/sys:/sys:ro", "--privileged"]
