supported_targets:
- raspberrypi4
- raspberrypi5
- reterminal
- reterminal-dm

distro:
  version: 0.1.0
  channel: apollo-edge

extensions:
  avocado-ext-docker:
    version: '{{ avocado.distro.version }}'
    release: r0
    summary: Avocado Docker container engine
    description: Avocado Docker container engine
    license: Apache-2.0
    url: https://github.com/avocadolinux/avocado-os
    vendor: Avocado Linux <info@avocadolinux.org>

    enable_services:
    - docker.service

    packages:
      docker: '*'
      kernel-module-br-netfilter: '*'
      kernel-module-bridge: '*'

sdk:
  image: docker.io/avocadolinux/sdk:{{ avocado.distro.channel }}
